version: "2.0"

services:
  documentinsight-backend-service:
    build:
      context: ../libs
      dockerfile: ./documentInsightsbacked
    depends_on:
      - elasticsearch
    ports:
    - 9494:9494
    links:
    - elasticsearch:elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK



